[package]
name = "hunter"
version = "0.1.0"
authors = ["project"]
edition = "2018"

[dependencies]
termion = "*"
unicode-width = "0.1.5"
lazy_static = "*"
x11-clipboard = "*"
alphanumeric-sort = "1.0.6"
lscolors = { version = "0.5.0", features = [ "ansi_term" ]  }
mime-detective = "*"
rayon = "1.0.3"
dirs-2 = "1.1.0"
users = "0.8"
chrono = "0.4"
libc = "*"
failure = "0.1.5"
failure_derive = "0.1.1"
notify = "4.0.9"
parse-ansi = "0.1.6"

#[profile.release]
#debug = true
#lto = false
